package com.rallyup.backend.domain.system.enum

enum class NotificationType {
    // 매칭 관련
    SIGNAL_RESPONSE, SIGNAL_MATCHED, SESSION_STARTING, SESSION_COMPLETED,

    // 클랜 관련
    CLAN_APPLICATION, CLAN_ACCEPTED, CLAN_REJECTED, CLAN_INVITED,
    CLAN_MEMBER_JOINED, CLAN_MEMBER_LEFT, CLAN_PROMOTION,

    // 피드백 관련
    FEEDBACK_RECEIVED, MANNER_SCORE_UPDATED,

    // 친구 관련
    FRIEND_REQUEST, FRIEND_ACCEPTED, FRIEND_ONLINE,

    // 시스템 관련
    SYSTEM_ANNOUNCEMENT, MAINTENANCE_NOTICE,

    // 프리미엄 관련
    PREMIUM_EXPIRING, PREMIUM_EXPIRED,

    // 기타
    WEEKLY_SUMMARY, ACHIEVEMENT_UNLOCKED
}